version: "3.8"

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/assistpro_kardex_fc
      - /var/www/html/assistpro_kardex_fc/vendor # Exclude vendor
    environment:
      # Configurar con credenciales de BD dev
      - DB_HOST=89.117.146.27
      - DB_PORT=3306
      - DB_NAME=assistpro_etl_fc_dev
      - DB_USER=root2
      - DB_PASS=AdvLogMysql21#
      - DB_CHARSET=utf8mb4
    restart: unless-stopped
